/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gondorSovereignIdentitySol from "./GondorSovereignIdentity.sol";
export type { gondorSovereignIdentitySol };
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
import type * as verifierWrapperSol from "./VerifierWrapper.sol";
export type { verifierWrapperSol };
import type * as test from "./test";
export type { test };
