/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISnarkJSVerifier } from "./ISnarkJSVerifier";
export type { VerifierWrapper } from "./VerifierWrapper";
