/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VerifierWrapperInterface extends Interface {
  getFunction(
    nameOrSignature: "snarkjsVerifier" | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "snarkjsVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "snarkjsVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export interface VerifierWrapper extends BaseContract {
  connect(runner?: ContractRunner | null): VerifierWrapper;
  waitForDeployment(): Promise<this>;

  interface: VerifierWrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  snarkjsVerifier: TypedContractMethod<[], [string], "view">;

  verifyProof: TypedContractMethod<
    [
      proof: BytesLike,
      tokenId: BigNumberish,
      oldTotalRevenue: BigNumberish,
      oldTotalCostInvested: BigNumberish,
      oldTotalCostRealized: BigNumberish,
      newTotalRevenue: BigNumberish,
      newTotalCostInvested: BigNumberish,
      newTotalCostRealized: BigNumberish,
      roots: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "snarkjsVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [
      proof: BytesLike,
      tokenId: BigNumberish,
      oldTotalRevenue: BigNumberish,
      oldTotalCostInvested: BigNumberish,
      oldTotalCostRealized: BigNumberish,
      newTotalRevenue: BigNumberish,
      newTotalCostInvested: BigNumberish,
      newTotalCostRealized: BigNumberish,
      roots: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
