/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGondorVerifier,
  IGondorVerifierInterface,
} from "../../../contracts/GondorSovereignIdentity.sol/IGondorVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "oldTotalRevenue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "oldTotalCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "oldTotalCostRealized",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newTotalRevenue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newTotalCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newTotalCostRealized",
        type: "uint256",
      },
      {
        internalType: "bytes32[]",
        name: "roots",
        type: "bytes32[]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGondorVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IGondorVerifierInterface {
    return new Interface(_abi) as IGondorVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGondorVerifier {
    return new Contract(address, _abi, runner) as unknown as IGondorVerifier;
  }
}
