/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GondorSovereignIdentity__factory } from "./GondorSovereignIdentity__factory";
export { IGondorVerifier__factory } from "./IGondorVerifier__factory";
