/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GondorSovereignIdentity } from "./GondorSovereignIdentity";
export type { IGondorVerifier } from "./IGondorVerifier";
