/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gondorSovereignIdentitySol from "./GondorSovereignIdentity.sol";
export * as verifierSol from "./Verifier.sol";
export * as verifierWrapperSol from "./VerifierWrapper.sol";
export * as test from "./test";
