// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Import OpenZeppelin ERC-721 and Ownable contracts
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @dev Interface for the external ZK verifier.
 * This allows swapping the ZK-SNARK logic without redeploying the identity contract.
 */
interface IGondorVerifier {
    function verifyProof(
        bytes calldata proof, 
        uint256 tokenId, 
        uint256 oldTotalRevenue, 
        uint256 oldTotalCost, 
        uint256 oldTotalCostRealized,
        uint256 newTotalRevenue, 
        uint256 newTotalCost, 
        uint256 newTotalCostRealized,
        bytes32[] calldata roots
    ) external view returns (bool);
}

/**
 * @title GondorSovereignIdentity
 * @dev Soulbound Token (SBT) representing a sovereign identity in the Gondor ecosystem.
 * Includes future-proof fields for reputation levels and heartbeat monitoring.
 */
contract GondorSovereignIdentity is ERC721, Ownable {
    uint256 private _nextTokenId;

    mapping(uint256 => string) public tokenDIDs;
    mapping(uint256 => uint256) public reputationLevels;
    mapping(uint256 => uint256) public reputationLevelsRealized;
    mapping(uint256 => uint256) public lastHeartbeat;

    // --- ZK SECURITY & VERIFIER ROUTING ---
    mapping(bytes32 => bool) public canonicalRoots;
    
    // Mapping: Batch Size (number of roots) => Verifier Contract Address
    // Example: verifiers[5] = FastVerifierAddress, verifiers[20] = MonthlyVerifierAddress
    mapping(uint256 => address) public verifiers; 
    
    bool private _isHandingOver;

    event ReputationUpdated(uint256 indexed tokenId, uint256 newLevel);
    event RootAnchored(bytes32 indexed root);
    event IdentityHandedOver(uint256 indexed tokenId, address indexed oldOwner, address indexed newOwner);
    event VerifierSet(uint256 indexed batchSize, address indexed verifierAddress);

    constructor() ERC721("GondorSovereignIdentity", "GSID") Ownable(msg.sender) {}

    /**
     * @dev Function to mint a new SBT. 
     * Only the owner (Pelargir backend) can call this function.
     * @param to User's wallet address.
     * @param did Decentralized Identifier generated by the system.
     */
    function safeMint(address to, string memory did) public onlyOwner returns (uint256) {
        uint256 tokenId = _nextTokenId++;
        tokenDIDs[tokenId] = did;
        
        // Initialize reputation level and heartbeat
        reputationLevels[tokenId] = 1; // Default starting level
        reputationLevelsRealized[tokenId] = 1;
        lastHeartbeat[tokenId] = block.timestamp;
        
        _safeMint(to, tokenId);

        return tokenId;
    }

    /**
     * @dev Anchors a Merkle Root of a transaction batch.
     * This allows future ZK proofs to be verified against this root.
     */
    function anchorRoot(bytes32 root) public onlyOwner {
        canonicalRoots[root] = true;
        emit RootAnchored(root);
    }

    /**
     * @dev Registers a new verifier for a specific batch size.
     * @param batchSize The number of transactions (roots) this verifier handles.
     * @param verifierAddress The address of the Gnark-generated verifier.
     */
    function setVerifier(uint256 batchSize, address verifierAddress) public onlyOwner {
        require(batchSize > 0, "Gondor: Batch size must be greater than 0");
        verifiers[batchSize] = verifierAddress;
        emit VerifierSet(batchSize, verifierAddress);
    }

    /**
     * @dev Transfers the identity to the user's personal wallet (Handover).
     * This is the only way an SBT can move.
     */
    function handoverSovereignty(uint256 tokenId, address newOwner) public onlyOwner {
        address currentOwner = _ownerOf(tokenId);
        require(currentOwner != address(0), "Gondor: Non-existent token");
        
        _isHandingOver = true;
        _transfer(currentOwner, newOwner, tokenId);
        _isHandingOver = false;
        
        emit IdentityHandedOver(tokenId, currentOwner, newOwner);
    }

    struct IdentityState {
        uint256 totalRevenue;
        uint256 totalCost; // Invested cost
        uint256 totalCostRealized; // Realized cost
    }
    mapping(uint256 => IdentityState) public identityStates; // La "Foto" de cada usuario

    /**
     * @dev Updates reputation using a ZK proof verified against anchored roots.
     * @param tokenId The ID of the identity to update.
     * @param newTotalRevenue The updated total revenue calculated by the ZK-SNARK.
     * @param newTotalCost The updated total cost calculated by the ZK-SNARK.
     * @param newTotalCostRealized The updated total cost realized calculated by the ZK-SNARK.
     * @param roots The Merkle Roots anchored in the contract.
     * @param proof The ZK-SNARK proof.
     */
    function updateReputationWithProof(
        uint256 tokenId, 
        uint256 newTotalRevenue,
        uint256 newTotalCost,
        uint256 newTotalCostRealized,
        bytes32[] calldata roots,
        bytes calldata proof
    ) public onlyOwner {
        require(_ownerOf(tokenId) != address(0), "Gondor: Non-existent token");
        require(roots.length > 0, "Gondor: Roots array cannot be empty");

        // 1. Find the correct verifier for this batch size
        address currentVerifier = verifiers[roots.length];
        require(currentVerifier != address(0), "Gondor: No verifier found for this batch size");

        // 2. Validate that every root provided is notarized
        for(uint256 i = 0; i < roots.length; i++) {
            if (roots[i] != bytes32(0)) {
                require(canonicalRoots[roots[i]], "Gondor: A root is not anchored");
            }
        }
        
        // 3. Prepare old state and call the specific ZK Verifier
        IdentityState memory oldState = identityStates[tokenId];
        
        bool isValid = IGondorVerifier(currentVerifier).verifyProof(
            proof, 
            tokenId, 
            oldState.totalRevenue, 
            oldState.totalCost, 
            oldState.totalCostRealized,
            newTotalRevenue, 
            newTotalCost, 
            newTotalCostRealized,
            roots
        );
        require(isValid, "Gondor: Invalid ZK proof");
        
        // Compute levels
        uint256 computedLevel = 0;
        if (newTotalCost > 0) {
            int256 diff = int256(newTotalRevenue) - int256(newTotalCost);
            int256 level = (diff * 100) / int256(newTotalCost);
            computedLevel = uint256(level);
        }

        uint256 computedLevelRealized = 0;
        if (newTotalCostRealized > 0) {
            int256 diff = int256(newTotalRevenue) - int256(newTotalCostRealized);
            int256 level = (diff * 100) / int256(newTotalCostRealized);
            computedLevelRealized = uint256(level);
        }

        // 4. Commit the new state to the blockchain
        identityStates[tokenId] = IdentityState(newTotalRevenue, newTotalCost, newTotalCostRealized);
        reputationLevels[tokenId] = computedLevel;
        reputationLevelsRealized[tokenId] = computedLevelRealized;
        lastHeartbeat[tokenId] = block.timestamp;

        emit ReputationUpdated(tokenId, computedLevel);
    }

    /**
     * @dev SOULBOUND LOGIC: Overrides the internal _update function of OpenZeppelin v5.
     * This is executed before any token movement.
     */
    function _update(address to, uint256 tokenId, address auth)
        internal
        override
        returns (address)
    {
        address from = _ownerOf(tokenId);
        
        // Allowed if Minting (from address(0)) or Burning (to address(0)) or Administrative Handover.
        // Any other transfer is blocked.
        require(from == address(0) || to == address(0) || _isHandingOver, "Gondor: SBT is non-transferable");

        return super._update(to, tokenId, auth);
    }
}
