import hre from "hardhat";
import fs from "fs";

async function main() {
  console.log("Starting the deployment of the new ZK Verifier...");

  // 1. Deploy the new Verifier contract (generated by snarkjs)
  const verifier = await hre.ethers.deployContract("Verifier");
  await verifier.waitForDeployment();
  const verifierAddress = verifier.target;
  console.log(`Success! New Verifier deployed at address: ${verifierAddress}`);

  // 2. We need the address of the main identity contract
  // If you save the contract address to a file during deploy.ts, you can read it here.
  // Assuming it's passed as an environment variable or we have to hardcode/fetch it.
  const identityAddress = process.env.IDENTITY_CONTRACT_ADDRESS;
  if (!identityAddress) {
      console.warn("WARNING: IDENTITY_CONTRACT_ADDRESS environment variable not set.");
      console.warn("The Verifier was deployed, but we cannot automatically call setVerifier().");
      console.warn("Please call GondorSovereignIdentity.setVerifier(5, '" + verifierAddress + "') manually.");
      return;
  }

  // 3. Connect to the Identity contract and update the verifier
  const identity = await hre.ethers.getContractAt("GondorSovereignIdentity", identityAddress);
  
  // We assume batch size is 5 based on your current circuit (BatchTxVerifier(5, 10))
  const batchSize = 5;
  console.log(`Updating GondorSovereignIdentity at ${identityAddress} to use new verifier for batch size ${batchSize}...`);
  
  const tx = await identity.setVerifier(batchSize, verifierAddress);
  await tx.wait();
  
  console.log("Success! Verifier updated on the blockchain.");
}

main().catch((error) => {
  console.error("Error during verifier update:", error);
  process.exitCode = 1;
});
